### ISSUE TITLE
When I am trying to "Sign in with Google" with a gmail account that is not associated with Knot, then I am getting this error.

### ISSUE THREAD

**Issue by ritesshg** [TuhinBar/Knot#19]
![image](https://user-images.githubusercontent.com/101876769/232242229-67035c3e-be43-4d9e-b829-4496c68abeaa.png)

**Comment by mirazxmondal** [comment]
I also faced the same issue!

**Comment by arian0zen** [comment]
we are looking forward to this.. will be fixed soon 🚨

**Comment by tuhinexe** [comment]
Issue resolved with PR #21 and #20

**Comment by ritesshg** [comment]
Thanks for this spontaneous bug fix ✋🏻
